version: '2'
services:
mysql:
    container_name: mysql
    image: mysql:5.7.16
    ports:
      - "9494:3306"
    restart: always
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=sonarqube
      - MYSQL_ROOT_PASSWORD=8jnYxnPlIAzP

  sonarqube:
    container_name: sonarqube
    image: sonarqube:6.3
    links:
      - mysql
    ports:
      - "9595:9000"
    restart: always
    volumes:
      - ./var/lib/sonarqube:/var/lib/postgresql
    environment:
      - SONARQUBE_JDBC_USERNAME=root
      - SONARQUBE_JDBC_PASSWORD=8jnYxnPlIAzP
      - SONARQUBE_JDBC_URL=jdbc:mysql://mysql:3306/sonarqube?useUnicode=true&&characterEncoding=utf8